### ISSUE TITLE
Request for Comment - Infinite Craft project compatibility meta tags

### ISSUE THREAD

**Issue by Spatchy** [helloyanis/Infinite-craft-memorizer#4]
Hi, I'm Spatchy, the developer of [Infinite Craft++](https://github.com/Spatchy/Infinite-Craft-Plus-Plus), another Infinite Craft extension.

I have been communicating with developers of several Infinite Craft projects and we have started to agree on a very simple communication scope to make projects (extensions, userscripts, etc.) that modify the game aware of other projects that are installed. The aim is to try and increase compatibility between projects so that end-users don't have to choose between one project or another, and to make things easier for the developers of such projects.

The currently proposed solution is for each project to add a `<meta ic-compat>` tag to the head of the page, containing information about itself that other projects can read and decide which of its own features it should enable or disable to prevent conflicts. I have [drafted a document proposing in more detail how these tags would work](https://github.com/Spatchy/Infinite-Craft-Plus-Plus/blob/chore/meta-tag-documentation/COMPAT.md). If you have any comments you would like to add, please respond to this issue or [issue #29 in the IC++ repo](https://github.com/Spatchy/Infinite-Craft-Plus-Plus/issues/29). We would greatly appreciate your input.

**Comment by helloyanis** [comment]
Heya, I don't think I really get it, how would adding the meta tag help compatibility between projects?
I think I understood the goal is to not have multiple addons/userscripts that do the same thing for users to chose, but how would that work?
I looked at the example tag and I don't get what's the difference between `features-avilable` and `features-enabled`? Because this add-on has several features (recipie saver, item export between browsers etc) and you can't just pick one to enable in the add-on, you just don't use the ones you dont care about

Can you please enlighten me?

**Comment by Spatchy** [comment]
This came about due to a conversation in discord between myself and Mikarific, the developer of [Infinite Craft Helper](https://github.com/Mikarific/InfiniteCraftHelper). The idea is basically just that the meta tag publicly shows the way a given extension is modifying the page. It's still completely up to the developer what they do with the information their project sees in other meta tags, but an imaginary scenario might look like this:

- Extension "E" and Userscript "U" both provide a conflicting feature "X"
- Developers of E and U agree that E should disable X if it detects U is running
- E sees the meta tag belonging to U and disables X
- E removes X from its own `features-enabled` field

The `features-enabled` field is there mainly to check that certain features are enabled or disabled, as agreements between developers may be more complex than outlined above (e.g. - user changeable settings may be involved). `features-available` is probably not useful in a majority of cases, it just lists all the features of a project, even the ones that are disabled, but it might be useful in some limited circumstances and there's no harm in including it.

I'm not asking you to make your project compatible with everything else using the tags (unless of course you want to), but just to provide your own meta tag so that developers who want to make stuff more compatible with your project can do so easier. Again, this is just a first draft so any ideas and input are welcomed.

**Comment by helloyanis** [comment]
Okay, I get it now!
I think I can add the meta tag in the next release
But I think it might not be the best choice, because of the following reasons :
- Nothing is being changed on the page itself by the add-on, so incompatibility would not really be an issue by other add-ons or userscript
- Therefore, other add-ons don't need to self-disable because nothing would become incompatible.
- Saving item recipies is done by reading the content of the web requests which can be done my multiple add-ons or userscripts, and the saving is done in the add-on localstorage so no other script can access it and conflict with it.
- Exporting and importing items is also done within the add-on page which is not accessible by anything else, and includes the item recipies from the add-on
- The only thing being changed is the local storage (to add items and import items) which only take effect after a page refresh, so I think that would ne why adding the tag would be a good thing

Tell me what you think about this!

**Comment by helloyanis** [comment]
Won't implement for the reasons above
